### PR TITLE
Changed dictionary structure

### PR DESCRIPTION
**Pull request by Kruno-S**
Dictionary restructure to be able to update it continuously and systematically. AFF-writen from scratch to represent the language structure (complete paradigms), added REP and INCONV section, use of affix alias. Replaced few incorrectly assigned classes in DIC-file.

### CODE REVIEW

**Comment by fitojb** [comment]
Hi @Kruno-S, this patch looks good to me. Can you send it through Gerrit? If you have any problems with that, please let me know and I will do it for you :smile_cat:

**Comment by Kruno-S** [comment]
Never used Gerrit but wiling to learn. I'll try to learn what needs to be learned and send it through Gerrit in a next day or two. I'll ask for help if stuck.

**Comment by Kruno-S** [comment]
I would like that you do it after all. I created Luncpad ID for LO Gerrit, tried to clone dictionaries folder and all but had hard time pushing the changes. Not comfortable doing that and I need to do some more reading but don't have time for that at the moment. I'll probably be ready for next update :) Thanks

**Comment by fitojb** [comment]
Don’t worry, I’m happy to help you while you learn to use the tools. For me to get the gist of Git, a couple of years had to pass :stuck_out_tongue: (I had only used Bazaar previously). If you mail me with the exact error that you experienced, probably I’ll be able to help you solve it.

So I’ve cherry-picked the four commits of this pull, squashed them into one, included your full name as author, and uploaded that combo to Gerrit: https://gerrit.libreoffice.org/23845

Note that I took the liberty of writing a commit message based on the four ones of each of your commits here. Feel free to review it.

If you want anything to be changed, or if my squashed commit contains errors (for some reason I’m prone to making mistakes :disappointed:), please poke me.

Thanks again!

**Comment by fitojb** [comment]
This got merged as commit de93f4fc07eba5fac0ae40bb45cc8e6acb331743

Thanks, Kruno!

**Comment by Kruno-S** [comment]
So I'm closing this then. 
Thanks.

**Pull request closed without merging**
